os: linux
dist: focal
language: go
go:
  - 1.7.x
jobs:
  include: 
  - name: “test123” # existing functionality
    script: # existing functionality
      - java -version
  - name: “sbom go”
    script: # existing functionality
      - java -version
    addons:
      sbom:
        on:
          branch: 'main'
          pr: false
        # condition: false
        run_phase: "after_success"
        output_format: "cyclonedx-json"
        output_dir: "/testggoutput"
        input_dir: "/testGO"
      deploy:
        provider: releases
        edge: true
        file_glob: true
        file: testggoutput/**/*
        skip_cleanup: true
        on:
         branch: main
